services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: loadtor-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - app-network
      - mongodb-network   # <-- add this to reach MongoDB

networks:
  app-network:
    driver: bridge
  mongodb-network:
    external: true       # because the network already exists