services:
  mongodb:
    image: mongo:7
    container_name: meta-crm-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5900"
    volumes:
      - /dev/shm:/dev/shm

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meta-crm-dev
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - MongoDB_URI=mongodb://root:root@mongodb:27017/?authSource=admin1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
      - selenium-hub

volumes:
  mongo_data:
