export const INDUSTRIES: string[] = [
    "Accounting",
    "Advertising",
    "Aerospace",
    "Agriculture",
    "Architecture",
    "Automotive",
    "Banking",
    "Biotechnology",
    "Chemical",
    "Construction",
    "Consulting",
    "Consumer Goods",
    "Defence",
    "Design",
    "E-Commerce",
    "Education",
    "Energy",
    "Entertainment",
    "Environmental",
    "Fashion",
    "Finance",
    "Food & Beverage",
    "Government",
    "Healthcare",
    "Hospitality",
    "HR",
    "Information Technology",
    "Insurance",
    "Legal",
    "Manufacturing",
    "Marketing",
    "Media",
    "Mining",
    "Non-Profit",
    "Oil & Gas",
    "Pharmaceutical",
    "Real Estate",
    "Retail",
    "SaaS",
    "Security",
    "Telecommunications",
    "Transportation",
    "Travel",
    "Utilities",
    "Venture Capital",
    "Wholesale",
];